---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
 - Launchpad
 - TV
 - Mail
 - Maps
 - Photos
 - FaceTime
 - Contacts
 - Music
 - Podcasts
 - Reminders
 - Notes
 - 'System Preferences'
 - 'App Store'
dockitems_persist:
 - name: "Brave Browser"
   path: "/Applications/Brave Browser.app/"
   pos: 2
 - name: "Spotfiy"
   path: "/Applications/Spotify.app/"
   pos: 3
 - name: "Books"
   path: "/Applications/Books.app/"
   pos: 4
 - name: "Kindle"
   path: "/Applications/Kindle.app/"
   pos: 5
 - name: "Calendar"
   path: "/Applications/Books.app/"
   pos: 6
 - name: "OmniFocus"
   path: "/Applications/OmniFocus.app/"
   pos: 7
 - name: "Evernote"
   path: "/Applications/Evernote.app/"
   pos: 8
 - name: "XMind"
   path: "/Applications/XMind.app/"
   pos: 9
 - name: "Scrivener"
   path: "/Applications/Scrivener.app/"
   pos: 10
 - name: "Affinity Photo"
   path: "/Applications/Affinity Photo.app/"
   pos: 11
 - name: "Affinity Designer"
   path: "/Applications/Affinity Designer.app/"
   pos: 12
 - name: "Pinegrow"
   path: "/Applications/Pinegrow.app/"
   pos: 14   
 - name: "PhpStorm"
   path: "/Applications/PhpStorm.app/"
   pos: 14
 - name: "Visual Studio Code"
   path: "/Applications/Visual Studio Code.app/"
   pos: 15
 - name: "iTerm"
   path: "/Applications/iTerm.app/"
   pos: 16
 - name: "Cyberduck"
   path: "/Applications/Cyberduck.app/"
   pos: 17
 - name: "Postman"
   path: "/Applications/Postman.app/"
   pos: 18
 - name: "Webex"
   path: "/Applications/Webex.app/"
   pos: 19
 - name: "MacPass"
   path: "/Applications/MacPass.app/"
   pos: 21
configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/openadviser/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .gitignore
  - .osx

homebrew_installed_packages:
  - autoconf
  - bash-completion
  - coreutils
  - doxygen
  - gettext
  - git
  - github/gh/gh
  - go
  - gpg
  - fzf
  - htop
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - midnight-commander
  - nmap
  - node
  - nvm
  - php
  - ssh-copy-id
  - tig
  - tmux
  - tree
  - openssl
  - youtube-dl
  - wget
  - wrk

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - appcleaner
  - audacity
  - bartender
  - balenaetcher
  - brave-browser
  - calibre
  - ccleaner
  - charles
  - cheatsheet
  - chromedriver
  - citrix-workspace
  - cyberduck
  - dash
  - dbeaver-community
  - disk-inventory-x
  - docker
  - dropbox
  - duet
  - evernote
  - firefox
  - flycut
  - google-chrome
  - google-drive
  - handbrake
  - hook
  - hyperswitch
  - iina
  - iterm2
  - itsycal
  - kindle
  - libreoffice
  - libreoffice-language-pack
  - licecap
  - malwarebytes
  - macpass
  - microsoft-office
  - microsoft-remote-desktop
  - microsoft-teams
  - ngrok
  - omnifocus
  - openrefine
  - poedit
  - postman
  - phpstorm
  - pinegrow
  - screens
  - scrivener
  - shuttle
  - sequel-ace
  - skitch
  - skype
  - slack
  - spectacle
  - spotify
  - stretchly
  - sublime-text
  - table-tool
  - the-unarchiver
  - vagrant
  - virtualbox
  - virtualbox-extension-pack
  - visual-studio-code
  - vlc
  - webex
  - xmind

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 824183456, name: "Affiniy Photo" }
  - { id: 824171161, name: "Affinity Designer" }    
  - { id: 937984704, name: "Amphetamine" }
mas_email: "info@openadviser.com"
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
